language: ruby
cache:
  bundler: true
  yarn: true
services:
  - redis-server
sudo: required
before_install:
- gem install bundler:2.0.2
- bundle install --jobs=3 --retry=3
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - postgresql-9.6-postgis-2.3-scripts
before_script:
  - psql -U postgres -c "create database newgps_test"
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d newgps_test

script: 
  - bundle exec rake db:test:prepare
  - bundle exec rspec